# Generated by Django 2.2.3 on 2019-07-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0004_restarunt_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='restarunt',
        ),
        migrations.DeleteModel(
            name='Restarunt',
        ),
    ]
