# Generated by Django 2.2.3 on 2019-07-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0005_auto_20190717_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='app_token',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
