version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build-prod

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: dist/painting-store
